name: CI

on:
  push:
    branches: [main]

jobs:

  build-binary-linux:
    timeout-minutes: 10
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on:
      labels: ubuntu-latest-large
    name: "Build on Linux"
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - name: "Setup musl"
        run: |
          sudo apt-get install musl-tools
          rustup target add x86_64-unknown-linux-musl
      - uses: Swatinem/rust-cache@v2
      - name: "Build"
        run: cargo build --target x86_64-unknown-linux-musl
      - name: "Upload binary"
        uses: actions/upload-artifact@v4
        with:
          name: uv-linux-${{ github.sha }}
          path: ./target/x86_64-unknown-linux-musl/debug/prompts
          retention-days: 1
